// Command genclient writes the TypeScript API client from docs/openapi.yaml.
package main

import (
	"fmt"
	"os"
	"strings"

	"gopkg.in/yaml.v3"
)

type document struct {
	Paths      yaml.Node `yaml:"paths"`
	Components struct {
		Schemas yaml.Node `yaml:"schemas"`
	} `yaml:"components"`
}

func main() {
	in := "docs/openapi.yaml"
	out := "web/src/generated/client.ts"
	if len(os.Args) == 3 {
		in, out = os.Args[1], os.Args[2]
	}
	raw, err := os.ReadFile(in)
	if err != nil {
		fatal(err)
	}
	var doc document
	if err := yaml.Unmarshal(raw, &doc); err != nil {
		fatal(err)
	}
	if doc.Components.Schemas.Kind != yaml.MappingNode || len(doc.Components.Schemas.Content) == 0 {
		fatal(fmt.Errorf("openapi components.schemas is empty"))
	}
	ops, err := operations(&doc.Paths)
	if err != nil {
		fatal(err)
	}
	if len(ops) == 0 {
		fatal(fmt.Errorf("openapi has no operations"))
	}
	var b strings.Builder
	b.WriteString("// Code generated by cmd/genclient from docs/openapi.yaml. DO NOT EDIT.\n\n")
	b.WriteString("export interface Operation {\n")
	b.WriteString("  operationId: string\n")
	b.WriteString("  method: 'GET' | 'POST' | 'PATCH' | 'PUT' | 'DELETE'\n")
	b.WriteString("  path: string\n")
	b.WriteString("  requestSchema: string\n")
	b.WriteString("}\n\n")
	b.WriteString("export const operations: Operation[] = [\n")
	bodyCount := 0
	for _, op := range ops {
		if op.schema != "" {
			bodyCount++
		}
		fmt.Fprintf(&b, "  { operationId: %q, method: %q, path: %q, requestSchema: %q },\n", op.id, op.method, op.path, op.schema)
	}
	b.WriteString("]\n\n")
	if bodyCount == 0 {
		fatal(fmt.Errorf("openapi has no requestBody schema"))
	}
	b.WriteString("export interface RequestOptions {\n")
	b.WriteString("  method: string\n")
	b.WriteString("  path: string\n")
	b.WriteString("  body?: unknown\n")
	b.WriteString("  headers?: Record<string, string>\n")
	b.WriteString("  csrf?: string\n")
	b.WriteString("}\n\n")
	b.WriteString("/** ApiError carries the HTTP status and the server error code. */\n")
	b.WriteString("export class ApiError extends Error {\n")
	b.WriteString("  status: number\n")
	b.WriteString("  code: string\n")
	b.WriteString("  requestId: string\n")
	b.WriteString("  retryAfter: number | null\n")
	b.WriteString("  constructor(status: number, code: string, message: string, requestId = '', retryAfter: number | null = null) {\n")
	b.WriteString("    super(message)\n")
	b.WriteString("    this.name = 'ApiError'\n")
	b.WriteString("    this.status = status\n")
	b.WriteString("    this.code = code\n")
	b.WriteString("    this.requestId = requestId\n")
	b.WriteString("    this.retryAfter = retryAfter\n")
	b.WriteString("  }\n")
	b.WriteString("}\n\n")
	b.WriteString("export async function requestJSON<T>(options: RequestOptions): Promise<T> {\n")
	b.WriteString("  const headers: Record<string, string> = { ...(options.headers ?? {}) }\n")
	b.WriteString("  if (options.body !== undefined) headers['Content-Type'] = 'application/json'\n")
	b.WriteString("  if (options.csrf && options.method !== 'GET') headers['X-CSRF-Token'] = options.csrf\n")
	b.WriteString("  let res: Response\n")
	b.WriteString("  try {\n")
	b.WriteString("    res = await fetch(options.path, {\n")
	b.WriteString("      method: options.method,\n")
	b.WriteString("      headers,\n")
	b.WriteString("      credentials: 'include',\n")
	b.WriteString("      body: options.body === undefined ? undefined : JSON.stringify(options.body),\n")
	b.WriteString("    })\n")
	b.WriteString("  } catch {\n")
	b.WriteString("    throw new ApiError(0, 'network', '无法连接到控制面')\n")
	b.WriteString("  }\n")
	b.WriteString("  const text = await res.text()\n")
	b.WriteString("  let json: { data?: T; error?: { code?: string; message?: string }; request_id?: string } = {}\n")
	b.WriteString("  if (text) {\n")
	b.WriteString("    try {\n")
	b.WriteString("      json = JSON.parse(text)\n")
	b.WriteString("    } catch {\n")
	b.WriteString("      if (!res.ok) throw new ApiError(res.status, 'invalid_response', text.slice(0, 200) || res.statusText)\n")
	b.WriteString("      throw new ApiError(res.status, 'invalid_response', '响应不是 JSON')\n")
	b.WriteString("    }\n")
	b.WriteString("  }\n")
	b.WriteString("  if (!res.ok) {\n")
	b.WriteString("    const retry = Number(res.headers.get('Retry-After'))\n")
	b.WriteString("    throw new ApiError(res.status, json.error?.code || 'http_' + res.status, json.error?.message || res.statusText || '请求失败', json.request_id || '', Number.isFinite(retry) && retry > 0 ? retry : null)\n")
	b.WriteString("  }\n")
	b.WriteString("  return json.data as T\n")
	b.WriteString("}\n")
	if err := os.MkdirAll("web/src/generated", 0o755); err != nil && !os.IsExist(err) {
		fatal(err)
	}
	if err := os.WriteFile(out, []byte(b.String()), 0o644); err != nil {
		fatal(err)
	}
}

type operation struct {
	id, method, path, schema string
}

func operations(paths *yaml.Node) ([]operation, error) {
	if paths.Kind != yaml.MappingNode {
		return nil, fmt.Errorf("paths is not a map")
	}
	var out []operation
	for i := 0; i+1 < len(paths.Content); i += 2 {
		path := paths.Content[i].Value
		methods := paths.Content[i+1]
		if methods.Kind != yaml.MappingNode {
			continue
		}
		for j := 0; j+1 < len(methods.Content); j += 2 {
			method := strings.ToUpper(methods.Content[j].Value)
			body := methods.Content[j+1]
			op := operation{method: method, path: path, schema: requestSchema(body)}
			op.id = field(body, "operationId")
			if op.id == "" {
				op.id = strings.ToLower(method) + "_" + strings.Trim(strings.ReplaceAll(path, "/", "_"), "_")
			}
			out = append(out, op)
		}
	}
	return out, nil
}

func requestSchema(op *yaml.Node) string {
	body := child(op, "requestBody")
	if body == nil {
		return ""
	}
	content := child(body, "content")
	jsonBody := child(content, "application/json")
	schema := child(jsonBody, "schema")
	if schema == nil {
		return ""
	}
	if ref := field(schema, "$ref"); ref != "" {
		return ref
	}
	return "inline"
}

func child(node *yaml.Node, key string) *yaml.Node {
	if node == nil || node.Kind != yaml.MappingNode {
		return nil
	}
	for i := 0; i+1 < len(node.Content); i += 2 {
		if node.Content[i].Value == key {
			return node.Content[i+1]
		}
	}
	return nil
}

func field(node *yaml.Node, key string) string {
	item := child(node, key)
	if item == nil {
		return ""
	}
	return item.Value
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
