// Package runner speaks the private NDJSON protocol and supervises one attempt.
// Agent stdout is captured. It is never promoted to a control event.
package runner

import (
	"bufio"
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"os/exec"
	"sync"
	"syscall"
	"time"

	"github.com/sllt/agentlab/internal/agent"
	"github.com/sllt/agentlab/internal/sandbox"
	"github.com/sllt/agentlab/internal/workspace"
)

const maxFrame = 1 << 20

type Spec struct {
	SchemaVersion string           `json:"schema_version"`
	AttemptID     string           `json:"attempt_id"`
	Fence         int64            `json:"fence"`
	Token         string           `json:"token"`
	WorkDir       string           `json:"work_dir"`
	BaselineDir   string           `json:"baseline_dir"`
	Prompt        string           `json:"prompt"`
	Executor      string           `json:"executor"`
	Network       string           `json:"network"`
	Launch        agent.LaunchSpec `json:"launch"`
	Limits        workspace.Limits `json:"limits"`
	WallSeconds   int              `json:"wall_seconds"`
	LogBytes      int64            `json:"log_bytes"`
	// ControlDir and HomeDir are outside the agent work tree. The journal in
	// ControlDir is not a signal source: recovery uses the control plane record.
	ControlDir string `json:"control_dir,omitempty"`
	HomeDir    string `json:"home_dir,omitempty"`
	TmpDir     string `json:"tmp_dir,omitempty"`
	// IdentityToken is generated by the control plane. The runner records the
	// live PID against it in memory. Recovery must not trust work/journal.json.
	IdentityToken string `json:"identity_token,omitempty"`
	// PassEnv names variables copied from the runner's own environment into the
	// agent's. The spec carries names only, never credential values.
	PassEnv []string `json:"pass_env,omitempty"`
	// Sandbox, when set, confines the agent with Landlock through the
	// "sandbox-exec" helper. If the helper cannot apply it the agent does
	// not start (fail closed).
	Sandbox *sandbox.Policy `json:"sandbox,omitempty"`
	// InheritHome gives the agent the real HOME instead of an empty one.
	InheritHome bool `json:"inherit_home,omitempty"`
}

type Event struct {
	SchemaVersion string          `json:"schema_version"`
	AttemptID     string          `json:"attempt_id"`
	Fence         int64           `json:"fence"`
	Sequence      int64           `json:"sequence"`
	ObservedAt    string          `json:"observed_at"`
	Origin        string          `json:"origin"`
	Type          string          `json:"type"`
	Payload       json.RawMessage `json:"payload,omitempty"`
}

type control struct {
	Type   string `json:"type"`
	Token  string `json:"token"`
	Reason string `json:"reason"`
	Spec   *Spec  `json:"spec"`
}

// Serve reads one Start from in, runs the attempt, and writes events to out.
// Closing in is treated as control-plane loss: the process tree is stopped.
func Serve(ctx context.Context, in io.Reader, out io.Writer) error {
	dec := json.NewDecoder(in)
	dec.UseNumber()
	var msg control
	if err := dec.Decode(&msg); err != nil {
		return err
	}
	if msg.Type != "Start" || msg.Spec == nil || msg.Token == "" || msg.Token != msg.Spec.Token {
		return errors.New("invalid start")
	}
	spec := msg.Spec
	if spec.Network == "restricted" || spec.Network == "offline" {
		return errors.New("network restriction is not enforced")
	}
	if spec.Executor != "" && spec.Executor != "native-trusted" {
		return fmt.Errorf("runner native path refuses executor %s", spec.Executor)
	}
	enableSubreaper()
	var seq int64
	var mu sync.Mutex
	emit := func(origin, typ string, payload any) error {
		mu.Lock()
		defer mu.Unlock()
		seq++
		ev := Event{SchemaVersion: "agentlab.event/v1", AttemptID: spec.AttemptID, Fence: spec.Fence, Sequence: seq, ObservedAt: time.Now().UTC().Format(time.RFC3339Nano), Origin: origin, Type: typ}
		if payload != nil {
			b, err := json.Marshal(payload)
			if err != nil {
				return err
			}
			ev.Payload = b
		}
		b, err := json.Marshal(ev)
		if err != nil {
			return err
		}
		b = append(b, '\n')
		_, err = out.Write(b)
		return err
	}
	if err := emit("runner", "Ready", map[string]string{"executor": spec.Executor, "network": spec.Network}); err != nil {
		return err
	}
	journal := controlJournal(spec)
	if err := writeJournal(journal, "armed", 0); err != nil {
		return err
	}
	if err := emit("runner", "PhaseChanged", map[string]string{"phase": "preparing"}); err != nil {
		return err
	}
	cancel := make(chan string, 1)
	readDone := make(chan struct{})
	go func() {
		defer close(readDone)
		for {
			var next control
			if err := dec.Decode(&next); err != nil {
				select {
				case cancel <- "control_lost":
				default:
				}
				return
			}
			if next.Type == "Cancel" || next.Type == "Shutdown" {
				reason := next.Reason
				if reason == "" {
					reason = next.Type
				}
				select {
				case cancel <- reason:
				default:
				}
				return
			}
		}
	}()
	if err := emit("runner", "PhaseChanged", map[string]string{"phase": "running"}); err != nil {
		return err
	}
	if err := writeJournal(journal, "started", 0); err != nil {
		return err
	}
	cmd, err := command(spec)
	if err != nil {
		_ = emit("runner", "Finished", map[string]any{"exit_code": -1, "error": err.Error(), "agent_started": false})
		return err
	}
	// StdoutPipe is closed by Wait before a concurrent reader is guaranteed to
	// finish, which drops the last lines. A writer makes Wait copy to completion
	// before it returns.
	stdoutR, stdoutW := io.Pipe()
	stderrR, stderrW := io.Pipe()
	cmd.Stdout = stdoutW
	cmd.Stderr = stderrW
	if err := cmd.Start(); err != nil {
		_ = stdoutW.Close()
		_ = stderrW.Close()
		_ = writeJournal(journal, "start_failed", 0)
		_ = emit("runner", "Finished", map[string]any{"exit_code": -1, "error": err.Error(), "agent_started": false})
		return nil
	}
	stopChild := func() {
		_ = killTree(cmd)
		_ = stdoutR.Close()
		_ = stderrR.Close()
		_ = cmd.Wait()
		_ = stdoutW.Close()
		_ = stderrW.Close()
	}
	if err := writeJournal(journal, "started", cmd.Process.Pid); err != nil {
		stopChild()
		return err
	}
	startTime, _ := ProcStartTime(cmd.Process.Pid)
	RememberIdentity(spec.IdentityToken, cmd.Process.Pid, startTime)
	if err := emit("runner", "IdentityRecorded", map[string]any{"pid": cmd.Process.Pid, "starttime": startTime, "token": spec.IdentityToken}); err != nil {
		stopChild()
		return err
	}
	logPath := filepathJoin(controlJournalDir(spec), "agent.log")
	logFile, err := os.Create(logPath)
	if err != nil {
		stopChild()
		return err
	}
	defer logFile.Close()
	var logBytes int64
	var truncated bool
	limit := spec.LogBytes
	if limit <= 0 {
		limit = 64 << 20
	}
	var logMu sync.Mutex
	stopGen := make(chan struct{})
	var stopOnce sync.Once
	signalStop := func() { stopOnce.Do(func() { close(stopGen) }) }
	secrets := forwardedSecrets(spec)
	consume := func(stream string, r io.Reader) {
		decode := agent.NewLineDecoder()
		reader := bufio.NewReaderSize(r, 64*1024)
		for {
			line, err := reader.ReadSlice('\n')
			if errors.Is(err, bufio.ErrBufferFull) {
				logMu.Lock()
				truncated = true
				logMu.Unlock()
				signalStop()
				continue
			}
			if len(line) > 0 {
				logMu.Lock()
				over := logBytes >= limit || int64(len(line)) > maxFrame
				if int64(len(line)) > maxFrame {
					line = line[:maxFrame]
				}
				line = redactSecrets(line, secrets)
				if !over && logBytes+int64(len(line)) <= limit {
					if _, werr := logFile.Write(line); werr != nil {
						truncated = true
						logMu.Unlock()
						signalStop()
						continue
					}
					logBytes += int64(len(line))
					events, decErr := decode.Decode(stream, line)
					logMu.Unlock()
					if decErr == nil {
						for _, ev := range events {
							if ev.Type == "Finished" || ev.Type == "CleanupCompleted" || ev.Type == "VerifiedPass" {
								ev.Type = "agent_event"
							}
							_ = emit(ev.Origin, ev.Type, json.RawMessage(ev.Payload))
						}
					}
				} else {
					truncated = true
					logMu.Unlock()
					signalStop()
				}
			}
			if err != nil {
				return
			}
		}
	}
	var wg sync.WaitGroup
	wg.Add(2)
	go func() { defer wg.Done(); consume("stdout", stdoutR) }()
	go func() { defer wg.Done(); consume("stderr", stderrR) }()
	// Wait copies into the pipes. Close them only after Wait so the copy can
	// finish, then wait until both readers have applied every line to the log.
	finishStreams := func() {
		_ = stdoutW.Close()
		_ = stderrW.Close()
		wg.Wait()
	}
	waitErr := make(chan error, 1)
	go func() { waitErr <- cmd.Wait() }()
	wall := spec.WallSeconds
	if wall <= 0 {
		wall = 60
	}
	timer := time.NewTimer(time.Duration(wall) * time.Second)
	defer timer.Stop()
	var exitErr error
	reason := ""
	select {
	case exitErr = <-waitErr:
	case reason = <-cancel:
		_ = stopManaged(cmd)
		exitErr = <-waitErr
	case <-timer.C:
		reason = "agent_time_limit"
		_ = stopManaged(cmd)
		exitErr = <-waitErr
	case <-ctx.Done():
		reason = "context"
		_ = stopManaged(cmd)
		exitErr = <-waitErr
	case <-stopGen:
		reason = "log_limit"
		_ = stopManaged(cmd)
		exitErr = <-waitErr
	}
	// Stop every process we can still see before reading the work tree.
	_ = stopManaged(cmd)
	finishStreams()
	code := 0
	if exitErr != nil {
		var ee *exec.ExitError
		if errors.As(exitErr, &ee) {
			code = ee.ExitCode()
		} else {
			code = -1
		}
	}
	proven := managedGone(cmd)
	_ = emit("runner", "LogSegmentCommitted", map[string]any{"path": "agent.log", "bytes": logBytes, "truncated": truncated, "proven": proven})
	cleanup := "clean"
	if !proven {
		cleanup = "quarantined"
		_ = emit("runner", "PatchCollected", map[string]any{"error": "cleanup_unproven"})
	} else {
		patch, patchErr := workspace.Collect(spec.BaselineDir, spec.WorkDir, spec.Limits)
		if patchErr != nil {
			_ = emit("runner", "PatchCollected", map[string]any{"error": patchErr.Error()})
		} else {
			_ = emit("runner", "PatchCollected", map[string]any{"digest": patch.Digest, "files": len(patch.Changes)})
			_ = os.WriteFile(filepathJoin(controlJournalDir(spec), "patch.json"), mustJSON(patch), 0o644)
		}
	}
	_ = emit("runner", "CleanupCompleted", map[string]string{"state": cleanup})
	// AuthenticationFailed is a runner decision from the execution spec the
	// control plane already froze. Agent stdout is not consulted.
	if spec.Launch.Env["AGENTLAB_FAKE_MODE"] == "auth" {
		_ = emit("runner", "AuthenticationFailed", map[string]string{"source": "fixture_mode"})
	}
	_ = emit("runner", "Finished", map[string]any{"exit_code": code, "reason": reason, "agent_started": true, "cleanup": cleanup, "truncated": truncated})
	return nil
}

func command(spec *Spec) (*exec.Cmd, error) {
	if spec.Launch.Executable == "" {
		return nil, errors.New("missing executable")
	}
	if spec.Executor != "native-trusted" && spec.Executor != "" {
		return nil, fmt.Errorf("runner native path refuses executor %s", spec.Executor)
	}
	cmd := exec.Command(spec.Launch.Executable, spec.Launch.Args...)
	if spec.Sandbox != nil {
		self, err := os.Executable()
		if err != nil {
			return nil, fmt.Errorf("sandbox helper: %w", err)
		}
		enc, err := spec.Sandbox.Encode()
		if err != nil {
			return nil, err
		}
		args := append([]string{"sandbox-exec", enc, "--", spec.Launch.Executable}, spec.Launch.Args...)
		cmd = exec.Command(self, args...)
	}
	cmd.Dir = spec.WorkDir
	cmd.Env = sanitizedEnv(spec)
	cmd.SysProcAttr = &syscall.SysProcAttr{Setpgid: true}
	return cmd, nil
}

func sanitizedEnv(spec *Spec) []string {
	allow := []string{"PATH", "LANG", "LC_ALL", "TZ"}
	var out []string
	for _, k := range allow {
		if v, ok := os.LookupEnv(k); ok {
			out = append(out, k+"="+v)
		}
	}
	home := spec.HomeDir
	if home == "" {
		home = filepathJoin(controlJournalDir(spec), "home")
	}
	tmp := spec.TmpDir
	if tmp == "" {
		tmp = filepathJoin(controlJournalDir(spec), "tmp")
	}
	_ = os.MkdirAll(home, 0o700)
	_ = os.MkdirAll(tmp, 0o700)
	if spec.InheritHome {
		if real, ok := os.LookupEnv("HOME"); ok && real != "" {
			home = real
			for _, k := range []string{"XDG_CONFIG_HOME", "XDG_DATA_HOME", "XDG_STATE_HOME", "XDG_CACHE_HOME"} {
				if v, ok := os.LookupEnv(k); ok {
					out = append(out, k+"="+v)
				}
			}
		}
	}
	out = append(out, "HOME="+home, "TMPDIR="+tmp)
	for _, k := range spec.PassEnv {
		if !agent.ValidCredentialEnv(k) {
			continue
		}
		if v, ok := os.LookupEnv(k); ok {
			out = append(out, k+"="+v)
		}
	}
	extra := spec.Launch.Env
	for k, v := range extra {
		switch k {
		case "PATH", "LANG", "LC_ALL", "TZ":
			out = append(out, k+"="+v)
		case "AGENTLAB_FAKE_MODE":
			out = append(out, k+"="+v)
		case "AGENTLAB_SOLUTION_DIR":
			if extra["AGENTLAB_FAKE_MODE"] != "" {
				out = append(out, k+"="+v)
			}
		}
	}
	return out
}

func controlJournalDir(spec *Spec) string {
	if spec.ControlDir != "" {
		return spec.ControlDir
	}
	return filepathJoin(os.TempDir(), "agentlab-control-"+spec.AttemptID)
}

func controlJournal(spec *Spec) string {
	return filepathJoin(controlJournalDir(spec), "journal.json")
}

func killTree(cmd *exec.Cmd) error {
	if cmd == nil || cmd.Process == nil {
		return nil
	}
	pid := cmd.Process.Pid
	_ = syscall.Kill(-pid, syscall.SIGTERM)
	deadline := time.Now().Add(300 * time.Millisecond)
	for time.Now().Before(deadline) {
		if syscall.Kill(-pid, 0) != nil {
			return nil
		}
		time.Sleep(20 * time.Millisecond)
	}
	return syscall.Kill(-pid, syscall.SIGKILL)
}

func processGroupGone(cmd *exec.Cmd) bool {
	if cmd == nil || cmd.Process == nil {
		return true
	}
	return syscall.Kill(-cmd.Process.Pid, 0) != nil
}

func writeJournal(path, state string, pid int) error {
	if err := os.MkdirAll(filepathDir(path), 0o755); err != nil {
		return err
	}
	f, err := os.OpenFile(path, os.O_CREATE|os.O_TRUNC|os.O_WRONLY, 0o644)
	if err != nil {
		return err
	}
	defer f.Close()
	if _, err := fmt.Fprintf(f, "{\"agent_start\":%q,\"pid\":%d}\n", state, pid); err != nil {
		return err
	}
	return f.Sync()
}

func mustJSON(v any) []byte {
	b, _ := json.Marshal(v)
	return b
}

func filepathJoin(elem ...string) string { return join(elem...) }
func filepathDir(path string) string     { return dir(path) }

// forwardedSecrets returns the values of forwarded credential variables that
// are long enough to redact without mangling ordinary output.
func forwardedSecrets(spec *Spec) [][]byte {
	var out [][]byte
	for _, k := range spec.PassEnv {
		if !agent.ValidCredentialEnv(k) {
			continue
		}
		if v, ok := os.LookupEnv(k); ok && len(v) >= 8 {
			out = append(out, []byte(v))
		}
	}
	return out
}

// redactSecrets replaces every forwarded credential value in an output line
// before the line reaches agent.log or the event stream.
func redactSecrets(line []byte, secrets [][]byte) []byte {
	for _, sec := range secrets {
		if bytes.Contains(line, sec) {
			line = bytes.ReplaceAll(line, sec, []byte("[REDACTED]"))
		}
	}
	return line
}
